version: "3.1"

services:
  app:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app:delegated
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  redis:
    image: redis
    ports:
      - "6379:6379"