version: "3.1"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app:delegated
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    environment:
      LOG_LEVEL: "INFO"
      URL: "https://ghibliapi.herokuapp.com"
      DEFAULT_CACHE_TIME: 40
      CLIENT: "http://localhost:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"