version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:delegated
    command: python /app/main.py

  redis:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'
