version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app:delegated
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 5000

  redis:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'
