version: "3.3"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      LOG_LEVEL: "INFO"
      URL: "https://ghibliapi.herokuapp.com"
      DEFAULT_CACHE_TIME: 40
      CLIENT: "http://localhost:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
      REACT_APP_API_ENDPOINT: "http://localhost:5000"
