version: '3.3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        LOG_LEVEL: 'INFO'
        CLIENT: 'http://localhost:8000'
    ports:
      - "5000:5000"
    
  redis:
    image: redis
    ports:
      - "6379:6379"

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    environment:
        API_ENDPOINT: 'http://localhost:5000' 